### ISSUE TITLE
Does not fly with Python 3.11

### ISSUE THREAD

**Issue by hholst80** [wbolster/evcape#13]
```
[I] (env) root@zink ~/evcape (master)# python3 evcape.py
Traceback (most recent call last):
  File "/home/root/evcape/evcape.py", line 10, in <module>
    import evdev
  File "/home/root/evcape/env/lib64/python3.11/site-packages/evdev/__init__.py", line 7, in <module>
    from evdev.device import DeviceInfo, InputDevice, AbsInfo
  File "/home/root/evcape/env/lib64/python3.11/site-packages/evdev/device.py", line 10, in <module>
    from evdev.eventio_async import EventIO
  File "/home/root/evcape/env/lib64/python3.11/site-packages/evdev/eventio_async.py", line 51, in <module>
    class ReadIterator(object):
  File "/home/root/evcape/env/lib64/python3.11/site-packages/evdev/eventio_async.py", line 73, in ReadIterator
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
[I] (env) root@zink ~/evcape (master) [0|1]#
```

**Comment by hholst80** [comment]
I think you need to vendor copy in the ev dependency to patch it.  The changes need the upstream API were trivial:

```
diff --git a/evcape.py b/evcape.py
index e2729cf..f85833d 100755
--- a/evcape.py
+++ b/evcape.py
@@ -59,9 +59,9 @@ def main():
         raise RuntimeError(
             f"could not access evdev device for uinput device {uinput.name!r}"
         )
-    logger.info(f"created uinput device {uinput.device.path}")
+    logger.info(f"created uinput device {uinput.device.fn}")

-    keyboard_monitor = KeyboardMonitor(ignored_devices=[uinput.device.path])
+    keyboard_monitor = KeyboardMonitor(ignored_devices=[uinput.device.fn])

     # the buffer is as long as the longest sequence in rules
     window_size = max(len(rule.patterns) for rule in rules)
@@ -130,7 +130,7 @@ class KeyboardMonitor:
         self.selector.register(
             input_device, events=selectors.EVENT_READ, data="keyboard"
         )
-        logger.info("monitoring {0.path} ({0.name})".format(input_device))
+        logger.info("monitoring {0.fn} ({0.name})".format(input_device))

     def remove_keyboard(self, device_name):
         for selector_key in self.selector.get_map().values():``
```

**Comment by hholst80** [comment]
env/lib/python3.11/site-packages/evdev/eventio_async.py" 89 lines
```
     73     async def __aiter__(self):
     74         return self
     75
     76     async def __anext__(self):
     77         future = asyncio.Future()
```

**Comment by hholst80** [comment]
In the end there seems to be a terminal timeout thing causing a type fast + tap on ctrl (caps lock) to not be interpreted as a esc.  Unless that can be fixed I don't see myself using this.  That is however another issue, maybe related to this Issue, IDK.
